"""Add password_hash to customers and sellers

Revision ID: 09bd007436c0
Revises: 40863c5bfc0b
Create Date: 2024-06-10 14:56:34.374813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '09bd007436c0'
down_revision = '40863c5bfc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('sellers', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'password_hash')
    op.drop_column('sellers', 'password_hash')
    # ### end Alembic commands ###
